CREATE TABLE PATIENT (
    ID INT(50) PRIMARY KEY,
    NAME CHAR(100) NOT NULL,
    PHONE_NO INT(10) NOT NULL,
    BLOOD_GROUP VARCHAR(5) NOT NULL,
    FBS FLOAT(10) NOT NULL,
    PPBS FLOAT(10) NOT NULL,
    BP FLOAT(10) NOT NULL,
    
)