CREATE TABLE PATIENT (
    ID INT(50) PRIMARY KEY,
    NAME CHAR(100) NOT NULL,
    PHONE_NO INT(10) NOT NULL,
    BLOOD_GROUP VARCHAR(5) NOT NULL,
    FBS FLOAT(10) NOT NULL,
    PPBS FLOAT(10) NOT NULL,
    BP FLOAT(10) NOT NULL,
    CREATININE FLOAT(10) NOT NULL,
    T3 FLOAT(10) NOT NULL,
    T4 FLOAT(10) NOT NULL,
    TSH FLOAT(10) NOT NULL,
    AST FLOAT(10) NOT NULL,
    ALT FLOAT(10) NOT NULL,
    ALP FLOAT(10) NOT NULL
)